# Generated by Django 3.2.3 on 2021-05-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('sujet', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='InfoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('tilte', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='images')),
                ('tilte2', models.CharField(max_length=200)),
                ('description2', models.TextField()),
            ],
            options={
                'verbose_name': 'InfoContact',
                'verbose_name_plural': 'InfoContacts',
            },
        ),
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Newsletters',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='TeamContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=255)),
                ('personne', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'TeamContact',
                'verbose_name_plural': 'TeamContact',
            },
        ),
    ]
