# Generated by Django 3.2.3 on 2021-05-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'CategorieService',
                'verbose_name_plural': 'CategorieServices',
            },
        ),
        migrations.CreateModel(
            name='CategorieWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'CategorieWork',
                'verbose_name_plural': 'CategorieWorks',
            },
        ),
        migrations.CreateModel(
            name='OptionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'OptionPricing',
                'verbose_name_plural': 'OptionPricings',
            },
        ),
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='images')),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('description3', models.TextField()),
            ],
            options={
                'verbose_name': 'PricingInfo',
                'verbose_name_plural': 'PricingInfos',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images')),
                ('description', models.TextField()),
                ('image2', models.FileField(upload_to='images')),
                ('description2', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categoriework')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images')),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.categorieservice')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('icon', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('prix', models.IntegerField()),
                ('color', models.BooleanField(default=False)),
                ('periode', models.CharField(max_length=250)),
                ('optionPricing', models.ManyToManyField(to='service.OptionPricing', verbose_name='optionPricing')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
            },
        ),
        migrations.CreateModel(
            name='ImageWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='images')),
                ('nom', models.CharField(max_length=250)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.work')),
            ],
            options={
                'verbose_name': 'ImageWork',
                'verbose_name_plural': 'ImageWorks',
            },
        ),
    ]
