# Generated by Django 3.2.3 on 2021-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_aboutinfo_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='option',
            field=models.ManyToManyField(null=True, to='siteweb.OptionAbout', verbose_name='OptionAbout'),
        ),
    ]
